name: untitled2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  video_player: ^2.10.1
  connectivity_plus: ^7.0.0
  shimmer: ^3.0.0
  flutter_svg: ^2.2.3
  audioplayers: ^6.5.1
  chewie: any
  file_picker: ^10.3.7






dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/mock/mock_data.json


